server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  swagger:
    title: 订单服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123