server:
  port: 8083
feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi

  swagger:
    title: 用户服务接口文档
    package: com.hm.user.controller
  db:
    database: hm-user
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123