server:
  port: 8082
spring:
  config:
    import: application-secret.yaml

feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  db:
    host: 8.130.9.216
    pw: ${secret.database.password}
    port: 3306
    name: hm-cart
  swagger:
    title: 黑马商城购物车接口文档
    describe: 购物车接口文档
    package: com.hmall.cart.controller


# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123