server:
  port: 8081
spring:
  application:
    name: item-service

  config:
    import: application-secret.yaml



hm:
  db:
    host: 8.130.9.216
    pw: ${secret.database.password}
    port: 3306
    name: hm-item
  swagger:
    title: 黑马商城商品管理接口文档
    description: "黑马商城商品管理接口文档"
    package: com.hmall.item.controller


# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123